### ISSUE TITLE
Mongo DB 구축

### ISSUE THREAD

**Issue by minkukjo** [depromeet/fire#3]

**Comment by levin-yu** [comment]
mongdb는 ec2에 직접 올리지 않고, 클라우드 altas에서 제공하는 프리티어를 이용해 구축해본다.

1. 프리티어로 aws 아시아 리전에 구축
2. robo 3t로 접속 확인.

**Comment by levin-yu** [comment]
아틀라스 프리티어로 클러스터를 생성하게 되면,  클러스터를 사용할 클라우드 사업자를 지정할 수 있다.
물리적인 거리를 감안하여, 서울이 없다면 가장 최적의 대안은 동북아시아(아시아-태평양 지역)이 될 것이다.

사업자는 aws, google, ms 세 회사가 있으며 회사별 제공하는 리전 지역은 다음과 같다.

AWS - 싱가폴, 뭄바이

Google - 타이완, 도쿄, 싱가폴, 뭄바이

Azule - 홍콩

도쿄가 물리적인 거리가 가장 가까우므로, Google로 선정해본다.

**Comment by levin-yu** [comment]
리전에 상관없이, 선택할 수 있는 티어는 3가지가 있다. 
RAM과 CPU는 모두 shared이며, 스토리지 용량과 시간당 요금에서 차이가 있다.

커넥션과 네트워크 속도도 모두 공통 사항으로 아래와 같다.

500 max connections
Low network performance
100 max databases
500 max collections.

티어별 용량은 다음과 같다.

M0 - 512MG, free
M2 - 2G, $9 / per month
M5 - 5G, $25 / per month

개발단계이고, 최대한 자금을 적게 쓰기 위해, M0로 선택한다.

**Comment by levin-yu** [comment]
추가 설정으로 mongodb 버전과 백업 여부를 선택할 수 있는데 M0에선 제공하지 않는다.

클러스터 이름은 프로젝트 이름과 통일하도록 한다.

**Comment by levin-yu** [comment]
클러스터를 생성했다면, 접속 설정을 할 수 있다.
기본 정책은 whitelist 기반으로 접속가능한 IP를 추가해주는 것이다. 
db는 우리 ec2와 각 개발자들의 기본 IP에서만 접속할 수 있도록 해본다.

db 사용자는 기본값으로 하나 생성하고, 별도로 공유하도록 한다.

**Comment by levin-yu** [comment]
기본 접속 설정을 한 후에는 접속 방법에 대해 설정할 수 있다. 하나를 설정하면 다른것을 쓰지 못하는 것은 아니다.

mongo shell이나 애플리케이션에서 쓸 수 있는 네이티브 드라이버, 혹은 mongo compass를 통해 접속 가능하다.

우선은 compass를 통해 접속할 수 있도록 한다..

**Comment by levin-yu** [comment]
접속 허용 IP는 언제든 변경 가능하다.

**Comment by levin-yu** [comment]
<img width="1256" alt="스크린샷 2020-09-09 오후 6 55 36" src="https://user-images.githubusercontent.com/4166057/92584002-13f17f00-f2ce-11ea-89c9-3a5586afa024.png">

이제 compass를 통해 접속이 가능하다.

**Comment by minkukjo** [comment]
역시 영평이형 고생했어!! 👍

**Comment by levin-yu** [comment]
DB접속 정보는 각자 메일로 초대한 클러스터의 connect 메뉴에서 확인 가능. 
비번은, 갠톡 주세요
